GET http://localhost:8000/recipes

###
POST http://localhost:8000/recipes
Content-Type: application/json

{
    "title": "Grilling with Nick",
    "description": "Meat!",
    "ingredients": [
        "🐄", "🐓"
    ]
}

###
GET http://localhost:8000/recipes/5ec907b300223dcc0078e781

###
GET http://localhost:8000/recipes/5ec907b300223dcc0078e782

### 
PATCH http://localhost:8000/recipes/5ec907b300223dcc0078e781
Content-Type: application/json

{
    "desc": "Veggies!!!1"
}

###
PATCH http://localhost:8000/recipes/5ec907b300223dcc0078e782
Content-Type: application/json

{
    "desc": "Invalid ID."
}

###
DELETE http://localhost:8000/recipes/5ec907b300223dcc0078e781

###
DELETE http://localhost:8000/recipes/5ec907b300223dcc0078e782