GET http://localhost:8000/recipes

###
POST http://localhost:8000/recipes
Content-Type: application/json

{
    "title": "Grilling with Nick",
    "desc": "Meat!",
    "ingredients": [
        "🐄", "🐓"
    ]
}

###
GET http://localhost:8000/recipes/5ec907b300223dcc0078e781

###
GET http://localhost:8000/recipes/5ec907b300223dcc0078e782